publish_mode: editorial_workflow
media_folder: static/images
public_folder: /images
backend:
  name: github
  branch: main
  repo: MarkRidings/lolcode-docs
  open_authoring: true
collections:
  - name: pages
    label: Pages
    files:
      - name: "home"
        label: "Home Page"
        file: "content/_index.md"
        fields:
          - widget: string
            name: title
            required: true
            hint: >-
              The title of the page
          - widget: markdown
            name: body
            label: Content
            required: true
            hint: Page content
  - name: docs
    label: Docs
    folder: /content/docs
    create: true
    extension: md
    slug: "{{slug}}"
    fields:
      - widget: string
        name: title
        label: Title
        required: true
        hint: >-
          The title of the page that will appear on the left nav
      - widget: number
        name: weight
        label: Weight
        required: false
        hint: >-
          The nav order of the page
      - widget: boolean
        name: bookToc
        label: Table of Contents
        required: false
        hint: >-
          If false, the right hand toc will not show. Defaults to true if empty
      - widget: boolean
        name: bookHiddean
        label: Hidden?
        required: false
        hint: >-
          If ture, the page will not list on the left hand nav
      - widget: markdown
        name: body
        label: Content
        required: true
        hint: Page content
